import User from "../models/User.js";
import Invitation from "../models/Invitation.js";
import asyncHandler from "express-async-handler";
import nodemailer from "nodemailer";
import crypto from "crypto"; // Add this import

// @desc Create invitation
// @route POST /api/admin/invitations
// @access Admin
export const createInvitation = asyncHandler(async (req, res) => {
  const { email, role } = req.body;

  if (!email || !role) {
    res.status(400);
    throw new Error("Please provide email and role");
  }

  // Check if user already exists
  const userExists = await User.findOne({ email });
  if (userExists) {
    res.status(400);
    throw new Error("User with this email already exists");
  }

  // Check for existing active invitation
  const existingInvitation = await Invitation.findOne({
    email: email.toLowerCase(),
    used: false,
    expiresAt: { $gt: new Date() }
  });

  if (existingInvitation) {
    res.status(400);
    throw new Error("Active invitation already exists for this email");
  }

  try {
    // Create invitation - let the model handle defaults for token and expiresAt
    const invitation = await Invitation.create({
      email: email.toLowerCase(),
      role,
      invitedBy: req.user._id
      // token and expiresAt will be auto-generated by model defaults
    });

    console.log("✅ Invitation created:", invitation);

    // Send invitation email (optional)
    try {
      await sendInvitationEmail(email, invitation.token, role);
    } catch (emailError) {
      console.log("Failed to send email:", emailError.message);
      // Continue even if email fails
    }

    res.status(201).json({
      _id: invitation._id,
      email: invitation.email,
      role: invitation.role,
      token: invitation.token,
      expiresAt: invitation.expiresAt,
      invitationLink: `${process.env.FRONTEND_URL || 'http://localhost:5173'}/register?token=${invitation.token}&email=${encodeURIComponent(email)}`
    });

  } catch (error) {
    console.error("❌ Error creating invitation:", error);
    
    // Handle specific MongoDB errors
    if (error.code === 11000) {
      res.status(400);
      throw new Error("Duplicate token generated. Please try again.");
    }
    
    res.status(400);
    throw new Error(`Failed to create invitation: ${error.message}`);
  }
});

// @desc Get all invitations
// @route GET /api/admin/invitations
// @access Admin
export const getInvitations = asyncHandler(async (req, res) => {
  const { page = 1, limit = 10, status = 'all' } = req.query;
  
  let query = {};
  
  if (status === 'active') {
    query = { used: false, expiresAt: { $gt: new Date() } };
  } else if (status === 'used') {
    query = { used: true };
  } else if (status === 'expired') {
    query = { used: false, expiresAt: { $lte: new Date() } };
  }

  const invitations = await Invitation.find(query)
    .populate('invitedBy', 'name email')
    .sort({ createdAt: -1 })
    .limit(limit * 1)
    .skip((page - 1) * limit);

  const total = await Invitation.countDocuments(query);

  res.status(200).json({
    invitations,
    totalPages: Math.ceil(total / limit),
    currentPage: page,
    total
  });
});

// @desc Resend invitation
// @route POST /api/admin/invitations/:id/resend
// @access Admin
export const resendInvitation = asyncHandler(async (req, res) => {
  const invitation = await Invitation.findById(req.params.id);
  
  if (!invitation) {
    res.status(404);
    throw new Error("Invitation not found");
  }

  if (invitation.used) {
    res.status(400);
    throw new Error("Invitation already used");
  }

  // Update expiration (extend by 7 days)
  invitation.expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
  await invitation.save();

  // Resend email
  try {
    await sendInvitationEmail(invitation.email, invitation.token, invitation.role);
  } catch (emailError) {
    console.log("Failed to send email:", emailError.message);
  }

  res.status(200).json({
    message: "Invitation resent successfully",
    invitationLink: `${process.env.FRONTEND_URL}/register?token=${invitation.token}&email=${encodeURIComponent(invitation.email)}`
  });
});

// @desc Delete invitation
// @route DELETE /api/admin/invitations/:id
// @access Admin
export const deleteInvitation = asyncHandler(async (req, res) => {
  const invitation = await Invitation.findById(req.params.id);
  
  if (!invitation) {
    res.status(404);
    throw new Error("Invitation not found");
  }

  await Invitation.findByIdAndDelete(req.params.id);

  res.status(200).json({ message: "Invitation deleted successfully" });
});

// @desc Get all users
// @route GET /api/admin/users
// @access Admin
export const getUsers = asyncHandler(async (req, res) => {
  const users = await User.find().select("-password").sort({ createdAt: -1 });
  res.status(200).json(users);
});

// @desc Update user role
// @route PATCH /api/admin/users/:id/role
// @access Admin
export const updateUserRole = asyncHandler(async (req, res) => {
  const { role } = req.body;
  
  if (!role) {
    res.status(400);
    throw new Error("Please provide role");
  }

  const user = await User.findById(req.params.id);
  
  if (!user) {
    res.status(404);
    throw new Error("User not found");
  }

  user.role = role;
  await user.save();

  res.status(200).json({
    _id: user._id,
    name: user.name,
    email: user.email,
    role: user.role
  });
});

// Helper function to send invitation email
const sendInvitationEmail = async (email, token, role) => {
  // Only send email if email configuration exists
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    console.log("Email configuration not found - skipping email send");
    return;
  }

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: { 
      user: process.env.EMAIL_USER, 
      pass: process.env.EMAIL_PASS 
    },
  });

  const invitationLink = `${process.env.FRONTEND_URL}/register?token=${token}&email=${encodeURIComponent(email)}`;

  const mailOptions = {
    from: process.env.EMAIL_USER,
    to: email,
    subject: "Invitation to Petrol Pump Management System",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #333;">You're Invited!</h2>
        <p>You have been invited to join the Petrol Pump Management System.</p>
        <p><strong>Role:</strong> ${role}</p>
        <p>Click the link below to create your account:</p>
        <a href="${invitationLink}" 
           style="display: inline-block; padding: 12px 24px; background-color: #007bff; color: white; text-decoration: none; border-radius: 4px;">
          Create Account
        </a>
        <p style="margin-top: 20px; color: #666;">
          This invitation link will expire in 7 days.
        </p>
        <p>Or copy this token: <code>${token}</code></p>
      </div>
    `,
  };

  await transporter.sendMail(mailOptions);
};

// @desc Delete user
// @route DELETE /api/admin/users/:id
// @access Admin
export const deleteUser = asyncHandler(async (req, res) => {
  const user = await User.findById(req.params.id);
  
  if (!user) {
    res.status(404);
    throw new Error("User not found");
  }

  // Prevent deleting yourself
  if (user._id.toString() === req.user._id.toString()) {
    res.status(400);
    throw new Error("You cannot delete your own account");
  }

  await User.findByIdAndDelete(req.params.id);

  res.status(200).json({ 
    success: true,
    message: "User deleted successfully" 
  });
});